title: Boni's Page
logo: 
description: Complex is better than complicated
show_downloads: false
google_analytics:
remote_theme: bonioloff/minimal
main_page: https://bonioloff.github.io
linkedin: https://www.linkedin.com/in/bonioloff
leetcode: https://leetcode.com/bonioloff
kaggle: https://www.kaggle.com/bonioloff
github:
  is_user_page: true
  is_project_page: false
